### ISSUE TITLE
kdbgscan throws 'Python int too large to convert to C long'

### ISSUE THREAD

**Issue by brakmic** [google/rekall#166]
Hi,

I've encountered an error while working with an aff4-image from a **Win7SP1x64** machine  (VirtualBox).

The image was created with **winpmem 2.1.post4**

My rekal version:

```
This is Rekall Version 1.5.2.post1 (Furka)
{'pep440': u'1.5.2.post1', u'rc': u'0', u'version': u'1.5.2', 'error': 'Not in a git repository.', u'codename': u'Furka', u'post': u'1'}
```

```
[1] output.aff4 19:28:15> kdbgscan
------------------------> kdbgscan()
2016-07-30 19:28:22,408:CRITICAL:rekall.1:Traceback (most recent call last):
  File "site-packages\rekall\session.py", line 840, in RunPlugin
  File "site-packages\rekall\plugin.py", line 678, in render
  File "site-packages\rekall\plugins\windows\kdbgscan.py", line 143, in collect
OverflowError: Python int too large to convert to C long

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-3-b544700a2c49> in <module>()
----> 1 kdbgscan()

C:\bin\Rekall\rekall\obj.pyc in __call__(self, *args, **kwargs)

C:\bin\Rekall\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)

C:\bin\Rekall\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)

C:\bin\Rekall\rekall\plugin.pyc in render(self, renderer, **options)

C:\bin\Rekall\rekall\plugins\windows\kdbgscan.pyc in collect(self)

OverflowError: Python int too large to convert to C long
[1] output.aff4 19:28:22>
```

I'm using Python 2 in a separate virtualenv. The same command with Volatility delivers the expected data so I assume that my Python 2 env is not defect.

Before posting here I've looked around but couldn't find anything related to the above error. There are several postings on SO regarding _int to C-long conversion_ but they weren't directly related to Rekall.

Kind regards,

**Comment by scudette** [comment]
Thanks for reporting. This should be fixed by d00b99673654f599cd036e56ca8432b755d8dcba.

**Comment by brakmic** [comment]
Many thanks for the fix.

I've reinstalled rekall from git by using: *python ./setup.py develop*

But surprisingly, I get this error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\session.py", line 1172, in __getitem__
    if getattr(self["session"].plugins, item):
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\session.py", line 151, in __getattr__
    plugin_cls = self.GetPluginClass(name)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\session.py", line 131, in GetPluginClass
    metadata = self.plugin_db.GetActivePlugin(name)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\plugin.py", line 924, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\plugins\windows\common.py", line 59, in is_active
    return (super(AbstractWindowsCommandPlugin, cls).is_active(session) and
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\plugin.py", line 385, in is_active
    session.profile != None)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\utils.py", line 982, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\session.py", line 1056, in profile
    res = self.GetParameter("profile_obj")
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\session.py", line 762, in GetParameter
    result = self._RunParameterHook(item)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\session.py", line 797, in _RunParameterHook
    result = hook.calculate()
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall_core-1.5.3rc1.dev2-py2.7.egg\rekall\plugins\guess_profile.py", line 830, in calculate
    "Unable to find a valid profile for this image. "
RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
```

Maybe I should open a new issue request?

**Comment by brakmic** [comment]
I created a new virtualenv with Python 2 and checked out the current sources from Git.
After doing `python setup.py develop` I was able to start a proper CLI and execute commands. 

Previously I've tried to install it via `python setup.py install` but the result wasn't the expected rekall-CLI. Instead it showed only the default python CLI prompt **>>>**.
There I had to use plugins as python functions, e.g. *pslist()* instead of *pslist* etc.

I've also followed the tutorial from [rekal-forensic.blogspot](http://rekall-forensic.blogspot.de/2015/09/installing-rekall-on-windows.html).

Now I'm not sure if I was just 'lucky' with my setup or if there is some more complex problem behind it.

My current version is:
```
This is Rekall Version 1.5.2.post1 (Furka)
{'pep440': u'1.5.2.post1', u'rc': u'0', u'version': u'1.5.2', 'error': 'Not in a git repository.', u'codename': u'Furka', u'post': u'1'}
```

**Comment by brakmic** [comment]
Just found out there was a similar issue with an older version of rekall (1.4.1).

https://github.com/google/rekall/issues/131

I've tried to increase the autodetect scan length but the problem remains.

**Comment by scudette** [comment]
Note that there are two packages, with two setup.py files. The top level
rekall package is just a meta package. You would want to install the one in
rekall-core.

**Comment by scudette** [comment]
Also head uses ipython version 5 and switches off ipython support if you
have the older one. So maybe that's why you see the basic python interface.
You could try to upgrade ipython with

pip install --upgrade ipython

**Comment by brakmic** [comment]
First, I've used the setup.py from rekall-core as I was following the tutorial from rekall-forensic.blogspot. But because of the two (unrelated) problems with the CLI and the image recognition I've tried to mitigate them by recreating the virtual-envs. This was the point where I ran into the CLI-problems. So I've deleted everything and reinstalled it again.

Now I'm running ' 1.5.2.post1 (Furka).' and the CLI works. 

The problem with `kdbgscan` remains.

```
[1] Default session 15:52:24> kdbgscan
----------------------------> kdbgscan()
2016-07-31 16:23:05,733:DEBUG:rekall.1:Running plugin (kdbgscan) with args (()) kwargs ({})
2016-07-31 16:23:05,983:DEBUG:rekall.1:Listed 217 processes using PsActiveProcessHead
2016-07-31 16:23:07,838:DEBUG:rekall.1:Listed 193 processes using CSRSS
2016-07-31 16:23:10,878:DEBUG:rekall.1:Listed 217 processes using PspCidTable
2016-07-31 16:23:10,956:DEBUG:rekall.1:Listed 215 processes using Sessions
2016-07-31 16:23:11,082:DEBUG:rekall.1:Listed 196 processes using Handles
2016-07-31 16:23:18,542:DEBUG:rekall.1:Switching to Kernel context
2016-07-31 16:23:18,543:DEBUG:rekall.1:Switching to Kernel context
2016-07-31 16:23:19,354:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\ntfs.gz
2016-07-31 16:23:19,374:ERROR:rekall.3:Fatal Error: Unable to open \\.\: (123, 'CreateFile', 'The filename, directory name, or volume label syntax is incorrect.')
2016-07-31 16:23:25,072:DEBUG:rekall.1:Switching to Kernel context
2016-07-31 16:23:25,476:DEBUG:rekall.1:Switching to Kernel context
2016-07-31 16:23:26,523:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\ntfs.gz
         Out<2> Plugin: kdbgscan
[1] Default session 16:23:30>
```
I assume that I'm having the same issue like the one mentioned in https://github.com/google/rekall/issues/131

**Comment by brakmic** [comment]
Well, I just tried to get a process list and provoked another error:

```
[1] Default session 16:23:30> psscan
----------------------------> psscan()
2016-07-31 16:27:47,805:DEBUG:rekall.1:Running plugin (psscan) with args (()) kwargs ({})
- _EPROCESS (P)          Name          PID    Offset(V)     PPID       PDB       Stat       Time created             Time exited
  -------------- -------------------- ----- -------------- ------ -------------- ---- ------------------------ ------------------------
2016-07-31 16:27:47,973:INFO:rekall.1:Scanning in: Pool NonPagedPoolNx (Node 0). [0xe00000000000-0xe00800000000]
2016-07-31 16:27:49,193:CRITICAL:rekall.1:Traceback (most recent call last):
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\session.py", line 840, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\plugin.py", line 678, in render
    for row in self.collect():
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\plugins\windows\filescan.py", line 424, in collect
    offset=run.start, maxlen=run.length):
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\plugins\windows\filescan.py", line 357, in scan
    for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\plugins\windows\common.py", line 342, in scan
    for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\scan.py", line 370, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\scan.py", line 261, in check_addr
    val = check.check(buffer_as, offset)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\plugins\windows\common.py", line 261, in check
    buffer_as, offset + self.tag_offset)
  File "c:\bin\anaconda\envs\python2\lib\site-packages\rekall\scan.py", line 174, in check
    if buffer_as.data.startswith(self.needle, buffer_offset):
TypeError: slice indices must be integers or None or have an __index__ method
```

**Comment by brakmic** [comment]
I've installed Linux Mint 4.4.0 and created a virtualenv with Python 2. 

```
Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I've checked out the latest sources and compiled everything. And it works flawlessly with the same image. 

```
[1] output.aff4 21:54:35> kdbgscan
------------------------> kdbgscan()
2016-07-31 21:54:35,293:DEBUG:rekall.1:Running plugin (kdbgscan) with args (()) kwargs ({})
Offset (V)                                         0xf80002853110
Offset (P)                                         0x2853110
KDBG owner tag check                               False
Version64                                          0xf800028530e8 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion)                      1
Build string (NtBuildLab)                          7601.23349.amd64fre.win7sp1_ldr.
PsActiveProcessHead                                0xf8000288a420 (34 processes)
PsLoadedModuleList                                 0xfffff800028a8730 (129 modules)
KernelBase                                         0xfffff80002666000 (Matches MZ: True)
Major (OptionalHeader)                             6
Minor (OptionalHeader)                             1
KPCR                                               0xf80002854d00 (CPU 0)
Out<21:54:37> Plugin: kdbgscan (KDBGScan)                    
[1] output.aff4 21:54:37> 
```
Either I'm doing something terribly wrong on my Windows 10 box or this issue appears only on Windows 10? :smile: 

Not sure what to do next :question:

**Comment by scudette** [comment]
Can you please post the command line you are using as well as the messages
printed with the -v flag.

**Comment by brakmic** [comment]
Of course.

Here's how it starts:
```
(python2) brakmic@kant ~/sources/rekall $ rekal -v -f /media/sf_share/DUMPS/testpc/output.aff4 
2016-08-01 00:03:41,379:DEBUG:rekall.1:Logging level set to 10
2016-08-01 00:03:41,385:DEBUG:rekall.1:Running plugin (shell) with args (()) kwargs ({'profile': None})

----------------------------------------------------------------------------
The Rekall Memory Forensic framework 1.5.3.rc1 (Furka).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
[1] output.aff4 00:03:42> 
```

and here a test with kdbgscan:

```
[1] output.aff4 00:05:15> kdbgscan
------------------------> kdbgscan()
2016-08-01 00:05:15,830:DEBUG:rekall.1:Running plugin (kdbgscan) with args (()) kwargs ({})
2016-08-01 00:05:15,838:DEBUG:rekall.1:Opened local file /home/brakmic/.rekall_cache/sessions/v1.0/sessions/32eba179c94586c40616b83b25908a8c1b012466/dtb.gz
2016-08-01 00:05:15,840:DEBUG:rekall.1:Decoded in 0.000736951828003 sec.
2016-08-01 00:05:15,843:DEBUG:rekall.1:Opened local file /home/brakmic/.rekall_cache/v1.0/nt/eprocess_index.gz
2016-08-01 00:05:16,023:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:/home/brakmic/.rekall_cache (in 0.180866003036 sec)
2016-08-01 00:05:16,034:DEBUG:rekall.1:Opened local file /home/brakmic/.rekall_cache/sessions/v1.0/sessions/32eba179c94586c40616b83b25908a8c1b012466/default_address_space.gz
2016-08-01 00:05:16,043:DEBUG:rekall.1:Decoded in 0.00530195236206 sec.
Offset (V)                                         0xf80002853110
Offset (P)                                         0x2853110
KDBG owner tag check                               False
Version64                                          0xf800028530e8 (Major: 15, Minor: 7601)
Service Pack (CmNtCSDVersion)                      1
Build string (NtBuildLab)                          7601.23349.amd64fre.win7sp1_ldr.
2016-08-01 00:05:18,127:DEBUG:rekall.1:Opened local file /home/brakmic/.rekall_cache/sessions/v1.0/sessions/32eba179c94586c40616b83b25908a8c1b012466/PsLoadedModuleList.gz
2016-08-01 00:05:18,138:DEBUG:rekall.1:Decoded in 0.0101590156555 sec.
PsActiveProcessHead                                0xf8000288a420 (34 processes)
PsLoadedModuleList                                 0xfffff800028a8730 (129 modules)
KernelBase                                         0xfffff80002666000 (Matches MZ: True)
2016-08-01 00:05:18,793:DEBUG:rekall.1:Opened local file /home/brakmic/.rekall_cache/v1.0/pe.gz
2016-08-01 00:05:18,882:INFO:rekall.1:Loaded profile pe from Local Cache Directory:/home/brakmic/.rekall_cache (in 0.0897099971771 sec)
Major (OptionalHeader)                             6
Minor (OptionalHeader)                             1
KPCR                                               0xf80002854d00 (CPU 0)
Out<00:05:19> Plugin: kdbgscan (KDBGScan)                    
[1] output.aff4 00:05:19> 
```

**Comment by scudette** [comment]
This seems to work. Did you say it was not working in Windows 10?

You might find it better to install from git head using pip:

pip install -e rekall/rekall-core/
pip install -e rekall/

Will effectively call setup.py develop but pip will make sure that all
the dependencies are already installed.

Are you running in live mode with Windows 10? Or are you trying to
open the same AFF4 image in windows 10?

Thanks
Michael.

**Comment by brakmic** [comment]
Yes, it works on Linux. The problems are only on my Windows 10 machine. 

And neither live mode not loading the image has worked on Win 10. 

I'll now try to install it from git-head and come back with more info...

**Comment by brakmic** [comment]
After having installed both eggs I'm getting some new errors related to `global_ns` keyword argument.

Here are the two install commands I used to install the packages:

```
pip install -e git+https://github.com/google/rekall.git#egg=rekall-core
pip install -e git+https://github.com/google/rekall.git#egg=rekall
```

This is what I get when running in live mode respective trying to load an image:

```
 (python2) C:\Users\Harris>rekal -v live
2016-08-01 00:31:28,473:DEBUG:rekall.1:Logging level set to 10
2016-08-01 00:31:28,490:DEBUG:rekall.1:Running plugin (live) with args (()) kwargs ({'profile': None, 'service_name': 'pmem', 'driver': None, 'device': '\\\\.\\pmem'})
Message
-------
Launching live memory analysis
2016-08-01 00:31:28,654:DEBUG:rekall.1:Unable to open \\.\pmem: (2, 'CreateFile', 'The system cannot find the file specified.')
2016-08-01 00:31:28,660:DEBUG:rekall.1:Loading driver from C:\bin\Anaconda\envs\python2\resources\WinPmem/winpmem_x64.sys
2016-08-01 00:31:28,663:DEBUG:rekall.1:Removing service pmem
2016-08-01 00:31:28,664:DEBUG:rekall.1:Stopping service: pmem
2016-08-01 00:31:28,750:DEBUG:rekall.1:Error stopping service: (1062, 'ControlService', 'The service has not been started.')
2016-08-01 00:31:28,750:DEBUG:rekall.1:Deleting service: pmem
2016-08-01 00:31:28,799:DEBUG:rekall.1:Created service pmem
C:\bin\Anaconda\envs\python2\lib\site-packages\IPython\core\interactiveshell.py:440: UserWarning: As of IPython 5.0 `PromptManager` config will have no effect and has been replaced by TerminalInteractiveShell.prompts_class
  warn('As of IPython 5.0 `PromptManager` config will have no effect'
2016-08-01 00:31:29,157:WARNING:rekall.1:Warning: IPython version 5.0.0 not fully supported. We recommend installing ipython version 4.
Python 2.7.12 |Anaconda 4.1.1 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
2016-08-01 00:31:30,217:DEBUG:rekall.1:Removing service pmem
2016-08-01 00:31:30,220:DEBUG:rekall.1:Stopping service: pmem
2016-08-01 00:31:30,262:DEBUG:rekall.1:Deleting service: pmem
2016-08-01 00:31:30,283:CRITICAL:rekall.1:Traceback (most recent call last):
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\rekall\session.py", line 840, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\rekall\plugin.py", line 678, in render
    for row in self.collect():
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\rekall\plugins\tools\live_windows.py", line 250, in collect
    shell.render(renderer)
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\rekall\plugins\tools\ipython.py", line 256, in render
    if not IPython012Support(self.session):
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\rekall\plugins\tools\ipython.py", line 52, in IPython012Support
    return ipython_support.Shell(user_session)
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\rekall\ipython_support.py", line 242, in Shell
    shell(global_ns=user_session.locals)
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\IPython\terminal\embed.py", line 156, in __call__
    global_ns=global_ns, compile_flags=compile_flags)
  File "C:\bin\Anaconda\envs\python2\lib\site-packages\IPython\terminal\embed.py", line 195, in mainloop
    raise DeprecationWarning("'global_ns' keyword argument is deprecated, and has been removed in IPython 5.0 use `module` keyword argument instead.")
DeprecationWarning: 'global_ns' keyword argument is deprecated, and has been removed in IPython 5.0 use `module` keyword argument instead.
```

**Comment by scudette** [comment]
Hi Harris,
  It looks like you still have the old code installed. Here is what I
did to install from head on Windows 10:

git clone https://github.com/google/rekall.git
cd rekall
c:\Python27\Scripts\virtualenv.exe c:\users\mic\test
\Users\\mic\test\Scripts\activate
pip install -e .\rekall-core
pip install -e .

Thanks
Michael.

**Comment by brakmic** [comment]
Hi Michael,

I've followed your advice and encountered yet another problem: 

```
pip install -U setuptools fails in fresh conda environment
```

As I'm using Anaconda Python environment there were some `extra` problems with execution of `easy_install.pth` scripts. Obviously, Anaconda was trying to execute a script that wasn't there.
```
Cannot remove entries from nonexistent file C:\bin\Anaconda\envs\python2\lib\site-pack
ages\easy-install.pth
```

Well, I had to google around for a bit and found a plenty of very similar issue reports, all linked to Anaconda. For example this one with TensorFlow: https://github.com/tensorflow/tensorflow/issues/135

Or this one: https://github.com/tensorflow/tensorflow/issues/622

As I'm not an expert regarding the inner mechanics of Anaconda and all these *pip, easy_install, conda, you-name-it-package-managers*, I've decided to remove Anaconda completely and install only a bare-bones Python27 distribution.

And it worked :smile: 

**live mode**

```
(test) D:\src\forensics\rekall>rekal -v live
2016-08-01 09:37:27,882:DEBUG:rekall.1:Logging level set to 10
2016-08-01 09:37:27,894:DEBUG:rekall.1:Running plugin (live) with args (()) kwargs ({'profile': None, 'service_name': 'pmem', 'driver': None, 'device': '\\\\.\\pmem', 'mode': 'Memory'})
Message
-------
Launching live memory analysis
2016-08-01 09:37:28,009:DEBUG:rekall.1:Unable to open \\.\pmem: (2, 'CreateFile', 'The system cannot find the file specified.')
2016-08-01 09:37:28,013:DEBUG:rekall.1:Loading driver from d:\src\forensics\rekall\rekall-core\resources\WinPmem\winpmem_x64.sys
2016-08-01 09:37:28,016:DEBUG:rekall.1:Removing service pmem
2016-08-01 09:37:28,019:DEBUG:rekall.1:pmem service does not exist.
2016-08-01 09:37:28,043:DEBUG:rekall.1:Created service pmem

----------------------------------------------------------------------------
The Rekall Memory Forensic framework 1.5.3.rc1.dev2 (Furka).

"We can remember it for you wholesale!"

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License.

See http://www.rekall-forensic.com/docs/Manual/tutorial.html to get started.
----------------------------------------------------------------------------
```

**kdbgscan**

```
[1] Live (Memory) 09:37:38> kdbgscan
2016-08-01 09:37:38,033:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-08-01 09:37:40,052:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-08-01 09:37:40,210:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\inventory.gz
2016-08-01 09:37:40,410:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-08-01 09:37:40,503:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\inventory.gz
2016-08-01 09:37:40,516:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\Linux\index.gz
2016-08-01 09:37:40,566:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0569999217987 sec)
2016-08-01 09:37:40,579:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\eprocess_index.gz
2016-08-01 09:37:40,743:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.173000097275 sec)
2016-08-01 09:37:40,779:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\index.gz
2016-08-01 09:37:41,127:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.355000019073 sec)
2016-08-01 09:37:41,138:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\OSX\index.gz
2016-08-01 09:37:41,144:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0139999389648 sec)
2016-08-01 09:37:41,157:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\pe.gz
2016-08-01 09:37:41,217:INFO:rekall.1:Loaded profile pe from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.069000005722 sec)
2016-08-01 09:37:41,220:DEBUG:rekall.1:Trying method pe, offset 0
2016-08-01 09:37:41,234:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-08-01 09:37:41,400:INFO:rekall.1:Found RSDS in kernel image: 29FFDD296DC84409BF627658B0BBCF1F1 (ntkrnlmp.pdb)
2016-08-01 09:37:41,414:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\GUID\29FFDD296DC84409BF627658B0BBCF1F1.gz
2016-08-01 09:37:42,311:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\undocumented.gz
2016-08-01 09:37:42,318:INFO:rekall.1:Loaded profile nt/undocumented from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0130000114441 sec)
2016-08-01 09:37:42,664:INFO:rekall.1:Loaded profile nt/GUID/29FFDD296DC84409BF627658B0BBCF1F1 from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 1.257999897 sec)
2016-08-01 09:37:42,759:INFO:rekall.1:Detected ntkrnlmp.pdb with GUID 29FFDD296DC84409BF627658B0BBCF1F1
2016-08-01 09:37:42,773:INFO:rekall.1:Detection method windows_kernel_file yielded profile <AMD64 profile nt/GUID/29FFDD296DC84409BF627658B0BBCF1F1 (Nt)>
--------------------------> kdbgscan()
2016-08-01 09:37:42,782:DEBUG:rekall.1:Running plugin (kdbgscan) with args (()) kwargs ({})
Out<09:37:46> Plugin: kdbgscan (KDBGScan)
[1] Live (Memory) 09:48:53>
```

**Comment by brakmic** [comment]
Well, there are another errors.

First, I've tried to read the **output.aff4** image (my VirtualBox Win7SP1x64 OS). But it failed with this error:

```
[1] output.aff4 10:17:44> psscan
2016-08-01 10:17:44,164:DEBUG:rekall.1:Voting round with base: None
2016-08-01 10:17:44,167:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2016-08-01 10:17:44,170:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2016-08-01 10:17:44,171:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2016-08-01 10:17:44,173:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: No base address space provided
2016-08-01 10:17:44,174:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2016-08-01 10:17:44,177:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Must stack on another address space
2016-08-01 10:17:44,178:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2016-08-01 10:17:44,180:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: No base address space provided
2016-08-01 10:17:44,183:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2016-08-01 10:17:44,269:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: No base address space provided
2016-08-01 10:17:44,289:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2016-08-01 10:17:44,292:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Must stack on another address space
2016-08-01 10:17:44,293:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2016-08-01 10:17:44,296:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Must stack on another address space
2016-08-01 10:17:44,298:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2016-08-01 10:17:44,299:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: No base address space provided
2016-08-01 10:17:44,301:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2016-08-01 10:17:44,302:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: No base address space provided
2016-08-01 10:17:44,305:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2016-08-01 10:17:44,306:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Must stack on another address space
2016-08-01 10:17:44,309:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2016-08-01 10:17:44,312:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Must be layered on another address space.
2016-08-01 10:17:44,313:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'>
2016-08-01 10:17:44,315:DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Filename does not look like a device.
2016-08-01 10:17:44,316:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2016-08-01 10:17:44,325:DEBUG:rekall.1:Unable to open AFF4 image Not found
2016-08-01 10:17:44,328:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Unable to open AFF4 volume
2016-08-01 10:17:44,329:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
2016-08-01 10:17:44,351:DEBUG:rekall.1:Succeeded instantiating Win32FileAddressSpace
2016-08-01 10:17:44,355:DEBUG:rekall.1:Voting round with base: Win32FileAddressSpace
2016-08-01 10:17:44,357:DEBUG:rekall.1:Trying <class 'rekall.plugins.response.common.APIDummyPhysicalAddressSpace'>
2016-08-01 10:17:44,358:DEBUG:rekall.1:Failed instantiating APIDummyPhysicalAddressSpace: Instantiation failed for unspecified reason
2016-08-01 10:17:44,359:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMSSAddressSpace'>
2016-08-01 10:17:44,371:DEBUG:rekall.1:Failed instantiating VMSSAddressSpace: Invalid VMware signature: 0x4034b50
2016-08-01 10:17:44,374:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.macho.MACHOCoreDump'>
2016-08-01 10:17:44,375:DEBUG:rekall.1:Failed instantiating MACHOCoreDump: Header signature invalid
2016-08-01 10:17:44,377:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.vmem.VMemAddressSpace'>
2016-08-01 10:17:44,378:DEBUG:rekall.1:Failed instantiating VMemAddressSpace: Only VMEM files supported.
2016-08-01 10:17:44,381:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.ewf.EWFAddressSpace'>
2016-08-01 10:17:44,385:DEBUG:rekall.1:Failed instantiating EWFAddressSpace: EWF signature not present
2016-08-01 10:17:44,388:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashBMP'>
2016-08-01 10:17:44,390:DEBUG:rekall.1:Failed instantiating WindowsCrashBMP: Header signature invalid
2016-08-01 10:17:44,391:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.KCoreAddressSpace'>
2016-08-01 10:17:44,394:DEBUG:rekall.1:Failed instantiating KCoreAddressSpace: Header signature invalid
2016-08-01 10:17:44,395:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace32'>
2016-08-01 10:17:44,398:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace32: Header signature invalid
2016-08-01 10:17:44,400:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.crash.WindowsCrashDumpSpace64'>
2016-08-01 10:17:44,401:DEBUG:rekall.1:Failed instantiating WindowsCrashDumpSpace64: Header signature invalid
2016-08-01 10:17:44,404:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.elfcore.Elf64CoreDump'>
2016-08-01 10:17:44,405:DEBUG:rekall.1:Failed instantiating Elf64CoreDump: Header signature invalid
2016-08-01 10:17:44,407:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.lime.LimeAddressSpace'>
2016-08-01 10:17:44,410:DEBUG:rekall.1:Failed instantiating LimeAddressSpace: Invalid Lime header signature
2016-08-01 10:17:44,411:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.WinPmemAddressSpace'>
2016-08-01 10:17:44,414:DEBUG:rekall.1:Failed instantiating WinPmemAddressSpace: Must be first Address Space
2016-08-01 10:17:44,414:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.aff4.AFF4AddressSpace'>
2016-08-01 10:17:44,424:DEBUG:rekall.1:Failed instantiating AFF4AddressSpace: Must stack on another address space
2016-08-01 10:17:44,426:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.win32.Win32FileAddressSpace'>
2016-08-01 10:17:44,427:DEBUG:rekall.1:Failed instantiating Win32FileAddressSpace: Must be first Address Space
2016-08-01 10:17:44,430:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pmem.MacPmemAddressSpace'>
2016-08-01 10:17:44,431:DEBUG:rekall.1:Failed instantiating MacPmemAddressSpace: Must be mapped directly over a raw device.
2016-08-01 10:17:44,434:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.FileAddressSpace'>
2016-08-01 10:17:44,436:DEBUG:rekall.1:Failed instantiating FileAddressSpace: Must be first Address Space
2016-08-01 10:17:44,437:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.mmap_address_space.MmapFileAddressSpace'>
2016-08-01 10:17:44,440:DEBUG:rekall.1:Failed instantiating MmapFileAddressSpace: Must be first Address Space
2016-08-01 10:17:44,441:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.amd64.VTxPagedMemory'>
2016-08-01 10:17:44,470:DEBUG:rekall.1:Failed instantiating VTxPagedMemory: No more EPTs specified
2016-08-01 10:17:44,473:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.standard.GlobalOffsetAddressSpace'>
2016-08-01 10:17:44,476:DEBUG:rekall.1:Failed instantiating GlobalOffsetAddressSpace: File offset not specified.
2016-08-01 10:17:44,477:DEBUG:rekall.1:Trying <class 'rekall.plugins.addrspaces.pagefile.PagefilePhysicalAddressSpace'>
2016-08-01 10:17:44,480:DEBUG:rekall.1:Failed instantiating PagefilePhysicalAddressSpace: Pagefile not specified
2016-08-01 10:17:44,482:INFO:rekall.1:Autodetected physical address space Win32FileAddressSpace
2016-08-01 10:17:44,506:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\sessions\v1.0\sessions\index.gz
2016-08-01 10:17:44,573:DEBUG:rekall.1:Decoded in 0.0639998912811 sec.
2016-08-01 10:17:44,578:DEBUG:rekall.1:Will detect profile using these Detectors: linux_index,nt_index,osx,pe,windows_kernel_file,rsds,ntfs,linux
2016-08-01 10:17:46,621:DEBUG:rekall.1:Opened url https://github.com/google/rekall-profiles/raw/master/v1.0/inventory.gz
2016-08-01 10:17:46,717:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\inventory.gz
2016-08-01 10:17:46,786:DEBUG:rekall.1:Opened url http://profiles.rekall-forensic.com/v1.0/inventory.gz
2016-08-01 10:17:46,885:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\inventory.gz
2016-08-01 10:17:46,898:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\Linux\index.gz
2016-08-01 10:17:46,950:INFO:rekall.1:Loaded profile Linux/index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0590000152588 sec)
2016-08-01 10:17:46,963:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\eprocess_index.gz
2016-08-01 10:17:47,124:INFO:rekall.1:Loaded profile nt/eprocess_index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.171000003815 sec)
2016-08-01 10:17:47,135:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\index.gz
2016-08-01 10:17:47,329:INFO:rekall.1:Loaded profile nt/index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.202999830246 sec)
2016-08-01 10:17:47,342:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\OSX\index.gz
2016-08-01 10:17:47,348:INFO:rekall.1:Loaded profile OSX/index from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0149998664856 sec)
2016-08-01 10:17:47,361:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\pe.gz
2016-08-01 10:17:47,585:INFO:rekall.1:Loaded profile pe from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.233000040054 sec)
2016-08-01 10:17:47,588:DEBUG:rekall.1:Trying method pe, offset 0
2016-08-01 10:17:47,599:DEBUG:rekall.1:Trying method windows_kernel_file, offset 0
2016-08-01 10:17:47,601:DEBUG:rekall.1:Trying method rsds, offset 0
2016-08-01 10:17:47,605:DEBUG:rekall.1:Trying method linux_index, offset 0
2016-08-01 10:17:47,607:DEBUG:rekall.1:LinuxIndexDetector:DetectFromHit(0) = None
2016-08-01 10:17:47,608:DEBUG:rekall.1:Trying method nt_index, offset 0
2016-08-01 10:17:47,611:DEBUG:rekall.1:Trying method ntfs, offset 0
2016-08-01 10:17:47,624:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\ntfs.gz
2016-08-01 10:17:47,634:INFO:rekall.1:Loaded profile ntfs from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0199999809265 sec)
2016-08-01 10:18:59,832:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\GUID\1C761A24099C47BCAB9B088F264D6D912.gz
2016-08-01 10:19:00,338:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\nt\undocumented.gz
2016-08-01 10:19:00,348:INFO:rekall.1:Loaded profile nt/undocumented from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.0160000324249 sec)
2016-08-01 10:19:00,627:INFO:rekall.1:Loaded profile nt/GUID/1C761A24099C47BCAB9B088F264D6D912 from Local Cache Directory:C:\Users\Harris\.rekall_cache (in 0.801000118256 sec)
2016-08-01 10:19:05,575:ERROR:rekall.1:No profiles match this image. Try specifying manually.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
c:\users\harris\test\lib\site-packages\IPython\core\prefilter.pyc in prefilter_lines(self, lines, continue_prompt)
    333                              for lnum, line in enumerate(llines) ])
    334         else:
--> 335             out = self.prefilter_line(llines[0], continue_prompt)
    336
    337         return out

c:\users\harris\test\lib\site-packages\IPython\core\prefilter.pyc in prefilter_line(self, line, continue_prompt)
    308             return normal_handler.handle(line_info)
    309
--> 310         prefiltered = self.prefilter_line_info(line_info)
    311         # print "prefiltered line: %r" % prefiltered
    312         return prefiltered

c:\users\harris\test\lib\site-packages\IPython\core\prefilter.pyc in prefilter_line_info(self, line_info)
    250         """
    251         # print "prefilter_line_info: ", line_info
--> 252         handler = self.find_handler(line_info)
    253         return handler.handle(line_info)
    254

c:\users\harris\test\lib\site-packages\IPython\core\prefilter.pyc in find_handler(self, line_info)
    257         for checker in self.checkers:
    258             if checker.enabled:
--> 259                 handler = checker.check(line_info)
    260                 if handler:
    261                     return handler

c:\users\harris\test\lib\site-packages\IPython\core\prefilter.pyc in check(self, line_info)
    413
    414     def check(self, line_info):
--> 415         obj = self.shell.user_ns.get(line_info.ifun)
    416         if isinstance(obj, Macro):
    417             return self.prefilter_manager.get_handler_by_name('macro')

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in get(self, item, default)
   1177     def get(self, item, default=None):
   1178         try:
-> 1179             return self[item]
   1180         except KeyError:
   1181             return default

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in __getitem__(self, item)
   1170             return super(DynamicNameSpace, self).__getitem__(item)
   1171         except KeyError:
-> 1172             if getattr(self["session"].plugins, item):
   1173                 return self._prepare_runner(item)
   1174

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in __getattr__(self, name)
    149         pslist_plugin = plugins.pslist()
    150         """
--> 151         plugin_cls = self.GetPluginClass(name)
    152         if plugin_cls == None:
    153             return plugin_cls

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in GetPluginClass(self, name)
    129         """
    130         # Try to see if the requested plugin is active right now.
--> 131         metadata = self.plugin_db.GetActivePlugin(name)
    132         if metadata == None:
    133             return metadata

d:\src\forensics\rekall\rekall-core\rekall\plugin.pyc in GetActivePlugin(self, plugin_name)
    922         for command_metadata in self.db.get(plugin_name, []):
    923             plugin_cls = command_metadata.plugin_cls
--> 924             if plugin_cls.is_active(self.session):
    925                 results.append(command_metadata)
    926

d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\common.pyc in is_active(cls, session)
     57     def is_active(cls, session):
     58         """We are only active if the profile is windows."""
---> 59         return (super(AbstractWindowsCommandPlugin, cls).is_active(session) and
     60                 session.profile.metadata("os") == 'windows')
     61

d:\src\forensics\rekall\rekall-core\rekall\plugin.pyc in is_active(cls, session)
    383             # autodetection in order to determine which plugins are active.
    384             profile = (super(ProfileCommand, cls).is_active(session) and
--> 385                        session.profile != None)
    386
    387             return profile

d:\src\forensics\rekall\rekall-core\rekall\utils.pyc in __get__(self, *args, **kwargs)
    980     def __get__(self, *args, **kwargs):
    981         try:
--> 982             return super(safe_property, self).__get__(*args, **kwargs)
    983         except AttributeError as e:
    984             message = "AttributeError raised: %s" % e

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in profile(self)
   1054             return process_context
   1055
-> 1056         res = self.GetParameter("profile_obj")
   1057         return res
   1058

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in GetParameter(self, item, default, cached)
    760         # can get if from a hook.
    761         try:
--> 762             result = self._RunParameterHook(item)
    763             if result is not None:
    764                 return result

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in _RunParameterHook(self, name)
    795                     self._hook_locks.add(name)
    796                     hook = cls(session=self)
--> 797                     result = hook.calculate()
    798
    799                     # Cache the output from the hook directly.

d:\src\forensics\rekall\rekall-core\rekall\plugins\guess_profile.pyc in calculate(self)
    828             if not profile_obj:
    829                 raise RuntimeError(
--> 830                     "Unable to find a valid profile for this image. "
    831                     "Try using -v for more details.")
    832

RuntimeError: Unable to find a valid profile for this image. Try using -v for more details.
[1] output.aff4 10:19:14>
```
Then I've tried to read from my host machine with **winpmem -l** and `rekal -v -f \\.\pmem`

```
----------------------------> psscan()
2016-08-01 10:13:24,049:DEBUG:rekall.1:Running plugin (psscan) with args (()) kwargs ({})
- _EPROCESS (P)          Name          PID    Offset(V)     PPID       PDB       Stat       Time created             Time exited
  -------------- -------------------- ----- -------------- ------ -------------- ---- ------------------------ ------------------------
2016-08-01 10:13:24,273:DEBUG:rekall.1:Listed 159 processes using PsActiveProcessHead
2016-08-01 10:13:26,029:DEBUG:rekall.1:Listed 146 processes using CSRSS
2016-08-01 10:13:29,220:DEBUG:rekall.1:Listed 159 processes using PspCidTable
2016-08-01 10:13:29,286:DEBUG:rekall.1:Listed 157 processes using Sessions
2016-08-01 10:13:29,398:DEBUG:rekall.1:Listed 149 processes using Handles
2016-08-01 10:13:29,469:DEBUG:rekall.1:Switching to Kernel context
2016-08-01 10:13:29,970:DEBUG:rekall.1:Switching to Kernel context
2016-08-01 10:13:29,970:DEBUG:rekall.1:Switching to Kernel context
2016-08-01 10:13:32,828:DEBUG:rekall.1:Switching to Kernel context
2016-08-01 10:13:32,831:DEBUG:rekall.1:Switching to Kernel context
2016-08-01 10:13:33,221:DEBUG:rekall.1:Switching to Kernel context
2016-08-01 10:13:33,650:DEBUG:root:Loaded configuration from C:\Users\Harris\.rekallrc
2016-08-01 10:13:33,654:DEBUG:rekall.2:Logging level set to 30
2016-08-01 10:13:33,661:DEBUG:rekall.1:Opened local file C:\Users\Harris\.rekall_cache\v1.0\ntfs.gz
2016-08-01 10:13:35,874:INFO:rekall.1:Scanning in: Pool NonPagedPoolNx (Node 0). [0xe00000000000-0xe00800000000]
2016-08-01 10:13:36,321:CRITICAL:rekall.1:Traceback (most recent call last):
  File "d:\src\forensics\rekall\rekall-core\rekall\session.py", line 860, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "d:\src\forensics\rekall\rekall-core\rekall\plugin.py", line 686, in render
    for row in self.collect():
  File "d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\filescan.py", line 424, in collect
    offset=run.start, maxlen=run.length):
  File "d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\filescan.py", line 357, in scan
    for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
  File "d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\common.py", line 345, in scan
    for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
  File "d:\src\forensics\rekall\rekall-core\rekall\scan.py", line 476, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "d:\src\forensics\rekall\rekall-core\rekall\scan.py", line 411, in check_addr
    val = check.check(buffer_as, offset)
  File "d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\common.py", line 264, in check
    buffer_as, offset + self.tag_offset)
  File "d:\src\forensics\rekall\rekall-core\rekall\scan.py", line 174, in check
    if buffer_as.data.startswith(self.needle, buffer_offset):
TypeError: slice indices must be integers or None or have an __index__ method

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-74285bbec4de> in <module>()
----> 1 psscan()

d:\src\forensics\rekall\rekall-core\rekall\obj.pyc in __call__(self, *args, **kwargs)
    137         new_kwargs = self._kwargs.copy()
    138         new_kwargs.update(kwargs)
--> 139         return self._target(*(self._args + args), **new_kwargs)
    140
    141     def get_default_arguments(self):

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
    861                 self.last = plugin_obj
    862             except (Exception, KeyboardInterrupt) as e:
--> 863                 self._HandleRunPluginException(ui_renderer, e)
    864
    865             finally:

d:\src\forensics\rekall\rekall-core\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
    858                     raise ValueError(
    859                         "Invalid plugin: %s" % original_plugin_obj)
--> 860                 result = plugin_obj.render(ui_renderer) or plugin_obj
    861                 self.last = plugin_obj
    862             except (Exception, KeyboardInterrupt) as e:

d:\src\forensics\rekall\rekall-core\rekall\plugin.pyc in render(self, renderer, **options)
    684
    685         renderer.table_header(self.table_header, **table_options)
--> 686         for row in self.collect():
    687             if isinstance(row, (list, tuple)):
    688                 renderer.table_row(*row, **options)

d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\filescan.pyc in collect(self)
    422
    423             for pool_obj, eprocess in scanner.scan(
--> 424                     offset=run.start, maxlen=run.length):
    425                 if run.data["type"] == "PhysicalAS":
    426                     # Switch address space from physical to virtual.

d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\filescan.pyc in scan(self, **kwargs)
    355
    356     def scan(self, **kwargs):
--> 357         for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
    358             # Also fetch freed objects.
    359             for object_header in pool_obj.IterObject("Process", freed=True):

d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\common.pyc in scan(self, offset, maxlen)
    343
    344         maxlen = maxlen or self.session.profile.get_constant("MaxPointer")
--> 345         for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
    346             yield self.session.profile._POOL_HEADER(
    347                 vm=self.address_space, offset=hit)

d:\src\forensics\rekall\rekall-core\rekall\scan.pyc in scan(self, offset, maxlen, end)
    474             while scan_offset < buffer_as.end():
    475                 # Check the current offset for a match.
--> 476                 res = self.check_addr(scan_offset, buffer_as=buffer_as)
    477
    478                 # Remove multiple matches in the overlap region which we

d:\src\forensics\rekall\rekall-core\rekall\scan.pyc in check_addr(self, offset, buffer_as)
    409         for check in self.constraints:
    410             # Ask the check if this offset is possible.
--> 411             val = check.check(buffer_as, offset)
    412
    413             # Break out on the first negative hit.

d:\src\forensics\rekall\rekall-core\rekall\plugins\windows\common.pyc in check(self, buffer_as, offset)
    262     def check(self, buffer_as, offset):
    263         return super(PoolTagCheck, self).check(
--> 264             buffer_as, offset + self.tag_offset)
    265
    266

d:\src\forensics\rekall\rekall-core\rekall\scan.pyc in check(self, buffer_as, offset)
    172         # Just check the buffer without needing to copy it on slice.
    173         buffer_offset = buffer_as.get_buffer_offset(offset) + self.needle_offset
--> 174         if buffer_as.data.startswith(self.needle, buffer_offset):
    175             return self.needle
    176

TypeError: slice indices must be integers or None or have an __index__ method
[1] Default session 10:14:46>
```

**Comment by brakmic** [comment]
I've set up another Windows-VM but this time it's an Win 8.1 x64 OS.
Rekal recognized the image without complaints.
I think my previous problems are only related to Win 10.

Here's my **pslist** output:

```
[1] output.aff4 22:50:35> pslist
------------------------> pslist()
2016-08-02 22:50:35,290:DEBUG:rekall.1:Running plugin (pslist) with args (()) kwargs ({})
  _EPROCESS            Name          PID   PPID   Thds    Hnds    Sess  Wow64           Start                     Exit
-------------- -------------------- ----- ------ ------ -------- ------ ------ ------------------------ ------------------------
2016-08-02 22:50:35,578:DEBUG:rekall.1:Listed 52 processes using PsActiveProcessHead
2016-08-02 22:50:38,473:DEBUG:rekall.1:Listed 47 processes using CSRSS
2016-08-02 22:50:42,249:DEBUG:rekall.1:Listed 49 processes using PspCidTable
2016-08-02 22:50:42,622:DEBUG:rekall.1:Listed 51 processes using Sessions
2016-08-02 22:50:43,321:DEBUG:rekall.1:Listed 47 processes using Handles
0xe00002833340                          0      0      0        -      - False  -                        -
0xe00002869740                          0 636980 647337        -      - False  -                        -
                                              96     52
0xe000000d3900 System                   4      0    103        -      - False  2016-08-02 20:39:12Z     -
0xe00000d9c080 WmiPrvSE.exe           124    752      6        -      0 False  2016-08-02 20:46:35Z     -
0xe000033ca080 svchost.exe            292    660     50        -      0 False  2016-08-02 20:39:27Z     -
0xe0000176f040 smss.exe               324      4      2        -      - False  2016-08-02 20:39:12Z     -
0xe00001eec540 svchost.exe            416    660     11        -      0 False  2016-08-02 20:39:28Z     -
0xe00003583580 svchost.exe            424    660     18        -      0 False  2016-08-02 20:39:27Z     -
0xe00001ee5400 svchost.exe            504    660     15        -      0 False  2016-08-02 20:39:28Z     -
0xe000023b3080 csrss.exe              516    412      9        -      0 False  2016-08-02 20:39:20Z     -
0xe00002336900 winpmem.exe            568   3940      1        -      1 True   2016-08-02 20:42:11Z     -
0xe00000156300 wininit.exe            572    412      1        -      0 False  2016-08-02 20:39:21Z     -
0xe0000016e080 csrss.exe              580    564     10        -      1 False  2016-08-02 20:39:21Z     -
0xe00002696080 winlogon.exe           636    564      2        -      1 False  2016-08-02 20:39:22Z     -
0xe00002762080 services.exe           660    572      2        -      0 False  2016-08-02 20:39:23Z     -
0xe00002730080 lsass.exe              672    572      6        -      0 False  2016-08-02 20:39:23Z     -
0xe00002aa01c0 svchost.exe            752    660     10        -      0 False  2016-08-02 20:39:26Z     -
0xe00002ad6900 svchost.exe            796    660      7        -      0 False  2016-08-02 20:39:26Z     -
0xe00001452900 VBoxService.ex         880    660     10        -      0 False  2016-08-02 20:39:27Z     -
0xe00001dcf900 McCSPServiceHo         892    660     14        -      0 False  2016-08-02 20:41:36Z     -
0xe00003cc3900 McAPExe.exe            904    660      8        -      0 False  2016-08-02 20:39:47Z     -
0xe00001449080 dwm.exe                908    636      8        -      1 False  2016-08-02 20:39:27Z     -
0xe00002b49900 svchost.exe            988    660     24        -      0 False  2016-08-02 20:39:27Z     -
0xe00003b6c900 mcsacore.exe          1060    660     33        -      0 False  2016-08-02 20:39:47Z     -
0xe0000367b080 spoolsv.exe           1104    660     11        -      0 False  2016-08-02 20:39:28Z     -
0xe000035fd900 svchost.exe           1152    660     21        -      0 False  2016-08-02 20:39:29Z     -
0xe00003725900 mfemms.exe            1324    660      8        -      0 False  2016-08-02 20:39:29Z     -
0xe000037be740 mfevtps.exe           1380    660      3        -      0 False  2016-08-02 20:39:29Z     -
0xe00003b54900 RuntimeBroker.        1416    752      2        -      1 False  2016-08-02 20:42:01Z     -
0xe00002086900 McUICnt.exe           1428    292     18        -      1 False  2016-08-02 20:40:37Z     -
0xe000037d2580 mfevtps.exe           1440   1324      5        -      0 False  2016-08-02 20:39:29Z     -
0xe00003754900 PEFService.exe        1476    660      3        -      0 False  2016-08-02 20:39:29Z     -
0xe0000373f080 mfefire.exe           1648   1324      8        -      0 False  2016-08-02 20:39:30Z     -
0xe0000395f7c0 McSvHost.exe          1808    660     82        -      0 False  2016-08-02 20:39:30Z     -
0xe000039d8080 dasHost.exe           1892    416      5        -      0 False  2016-08-02 20:39:31Z     -
0xe000038cd900 svchost.exe           1988    660     16        -      0 False  2016-08-02 20:39:30Z     -
0xe0000200c900 conhost.exe           2072   3940      2        -      1 False  2016-08-02 20:40:49Z     -
0xe00003b98900 taskhostex.exe        2424    292      7        -      1 False  2016-08-02 20:39:36Z     -
0xe00003bac680 explorer.exe          2432   2404     61        -      1 False  2016-08-02 20:39:36Z     -
0xe00003b6e900 ClassicStartMe        2560   2432      1        -      1 False  2016-08-02 20:39:36Z     -
0xe00001030900 McClientAnalyt        2620    752      5        -      0 False  2016-08-02 20:44:09Z     -
0xe0000390f380 mfefire.exe           2632    660      3        -      0 False  2016-08-02 20:39:47Z     -
0xe00003b4e080 mcshield.exe          2644   1324     42        -      0 False  2016-08-02 20:39:47Z     -
0xe00003c9e080 SearchIndexer.        2688    660     13        -      0 False  2016-08-02 20:39:37Z     -
0xe00003bc2080 WmiPrvSE.exe          2780    752      5        -      0 False  2016-08-02 20:43:37Z     -
0xe000016eb7c0 WWAHost.exe           2920    752     27        -      1 False  2016-08-02 20:42:00Z     -
0xe000032b4340 ModuleCoreServ        3160    660     31        -      0 False  2016-08-02 20:41:41Z     -
0xe0000216e080 svchost.exe           3216    660      4        -      0 False  2016-08-02 20:39:49Z     -
0xe00004038500 SettingSyncHos        3400    752      9        -      1 False  2016-08-02 20:41:39Z     -
0xe00003b0f900 svchost.exe           3408    660      3        -      0 False  2016-08-02 20:39:54Z     -
0xe000020c0080 VBoxTray.exe          3580   2432     12        -      1 False  2016-08-02 20:39:54Z     -
0xe00001e8c900 WSHost.exe            3880    752      6        -      1 False  2016-08-02 20:42:02Z     -
0xe00002a15780 cmd.exe               3940   2432      1        -      1 False  2016-08-02 20:40:49Z     -
0xe000021cb080 WMIADAP.exe           4092    292      0        -      0 False  2016-08-02 20:43:37Z     2016-08-02 20:47:58Z
0xe0000088e650 ���� ��♫aG@          21139 248765 326258        -      0 False  -                        -
               ���O                 25996   9271   2649
Out<22:50:45> Plugin: pslist (WinPsList)
```

and **kdbgscan**:

```
[1] output.aff4 22:50:50> kdbgscan
------------------------> kdbgscan()
2016-08-02 22:50:50,088:DEBUG:rekall.1:Running plugin (kdbgscan) with args (()) kwargs ({})
2016-08-02 22:50:58,321:DEBUG:rekall.1:Switching to Kernel context
2016-08-02 22:50:58,325:DEBUG:rekall.1:Switching to Kernel context
2016-08-02 22:51:20,474:DEBUG:rekall.1:Switching to Kernel context
2016-08-02 22:51:22,342:DEBUG:rekall.1:Switching to Kernel context
Out<22:51:26> Plugin: kdbgscan (KDBGScan)
```

**Comment by scudette** [comment]
The kdbgscan plugin will not work on more recent versions of windows 8.1 because the KDBG block is obfuscated on those versions. Pslist should be working fine though. 

It looks like pslist works ok but psscan is not working. could you please try to print some of the values:

in the interactive console type pdb enter
then run psscan
when it breaks you will be in the location where it last broke
print repr(self.needle), repr(buffer_offset)

**Comment by brakmic** [comment]
Here's the output:

```
[1] Live (Memory) 23:50:43> pdb
Automatic pdb calling has been turned ON
[1] Live (Memory) 23:50:49> psscan
--------------------------> psscan()
2016-08-02 23:50:49,753:DEBUG:rekall.1:Running plugin (psscan) with args (()) kwargs ({})
- _EPROCESS (P)          Name          PID    Offset(V)     PPID       PDB       Stat       Time created             Time exited
  -------------- -------------------- ----- -------------- ------ -------------- ---- ------------------------ ------------------------
2016-08-02 23:50:50,121:DEBUG:rekall.1:Listed 198 processes using PsActiveProcessHead
2016-08-02 23:50:52,757:DEBUG:rekall.1:Listed 173 processes using CSRSS
2016-08-02 23:50:56,872:DEBUG:rekall.1:Listed 196 processes using Sessions
2016-08-02 23:50:57,046:DEBUG:rekall.1:Listed 176 processes using Handles
2016-08-02 23:51:04,325:DEBUG:rekall.1:Listed 198 processes using PspCidTable
2016-08-02 23:51:04,362:INFO:rekall.1:Scanning in: Pool NonPagedPoolNx (Node 0). [0xe00000000000-0xe00800000000]
2016-08-02 23:51:04,954:CRITICAL:rekall.1:Traceback (most recent call last):
  File "d:\src\python\rekall\rekall-core\rekall\session.py", line 860, in RunPlugin
    result = plugin_obj.render(ui_renderer) or plugin_obj
  File "d:\src\python\rekall\rekall-core\rekall\plugin.py", line 686, in render
    for row in self.collect():
  File "d:\src\python\rekall\rekall-core\rekall\plugins\windows\filescan.py", line 424, in collect
    offset=run.start, maxlen=run.length):
  File "d:\src\python\rekall\rekall-core\rekall\plugins\windows\filescan.py", line 357, in scan
    for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
  File "d:\src\python\rekall\rekall-core\rekall\plugins\windows\common.py", line 345, in scan
    for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
  File "d:\src\python\rekall\rekall-core\rekall\scan.py", line 476, in scan
    res = self.check_addr(scan_offset, buffer_as=buffer_as)
  File "d:\src\python\rekall\rekall-core\rekall\scan.py", line 411, in check_addr
    val = check.check(buffer_as, offset)
  File "d:\src\python\rekall\rekall-core\rekall\plugins\windows\common.py", line 264, in check
    buffer_as, offset + self.tag_offset)
  File "d:\src\python\rekall\rekall-core\rekall\scan.py", line 174, in check
    if buffer_as.data.startswith(self.needle, buffer_offset):
TypeError: slice indices must be integers or None or have an __index__ method

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-74285bbec4de> in <module>()
----> 1 psscan()

d:\src\python\rekall\rekall-core\rekall\obj.pyc in __call__(self, *args, **kwargs)
    137         new_kwargs = self._kwargs.copy()
    138         new_kwargs.update(kwargs)
--> 139         return self._target(*(self._args + args), **new_kwargs)
    140
    141     def get_default_arguments(self):

d:\src\python\rekall\rekall-core\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
    861                 self.last = plugin_obj
    862             except (Exception, KeyboardInterrupt) as e:
--> 863                 self._HandleRunPluginException(ui_renderer, e)
    864
    865             finally:

d:\src\python\rekall\rekall-core\rekall\session.pyc in RunPlugin(self, plugin_obj, *args, **kwargs)
    858                     raise ValueError(
    859                         "Invalid plugin: %s" % original_plugin_obj)
--> 860                 result = plugin_obj.render(ui_renderer) or plugin_obj
    861                 self.last = plugin_obj
    862             except (Exception, KeyboardInterrupt) as e:

d:\src\python\rekall\rekall-core\rekall\plugin.pyc in render(self, renderer, **options)
    684
    685         renderer.table_header(self.table_header, **table_options)
--> 686         for row in self.collect():
    687             if isinstance(row, (list, tuple)):
    688                 renderer.table_row(*row, **options)

d:\src\python\rekall\rekall-core\rekall\plugins\windows\filescan.pyc in collect(self)
    422
    423             for pool_obj, eprocess in scanner.scan(
--> 424                     offset=run.start, maxlen=run.length):
    425                 if run.data["type"] == "PhysicalAS":
    426                     # Switch address space from physical to virtual.

d:\src\python\rekall\rekall-core\rekall\plugins\windows\filescan.pyc in scan(self, **kwargs)
    355
    356     def scan(self, **kwargs):
--> 357         for pool_obj in super(PoolScanProcess, self).scan(**kwargs):
    358             # Also fetch freed objects.
    359             for object_header in pool_obj.IterObject("Process", freed=True):

d:\src\python\rekall\rekall-core\rekall\plugins\windows\common.pyc in scan(self, offset, maxlen)
    343
    344         maxlen = maxlen or self.session.profile.get_constant("MaxPointer")
--> 345         for hit in super(PoolScanner, self).scan(offset=offset, maxlen=maxlen):
    346             yield self.session.profile._POOL_HEADER(
    347                 vm=self.address_space, offset=hit)

d:\src\python\rekall\rekall-core\rekall\scan.pyc in scan(self, offset, maxlen, end)
    474             while scan_offset < buffer_as.end():
    475                 # Check the current offset for a match.
--> 476                 res = self.check_addr(scan_offset, buffer_as=buffer_as)
    477
    478                 # Remove multiple matches in the overlap region which we

d:\src\python\rekall\rekall-core\rekall\scan.pyc in check_addr(self, offset, buffer_as)
    409         for check in self.constraints:
    410             # Ask the check if this offset is possible.
--> 411             val = check.check(buffer_as, offset)
    412
    413             # Break out on the first negative hit.

d:\src\python\rekall\rekall-core\rekall\plugins\windows\common.pyc in check(self, buffer_as, offset)
    262     def check(self, buffer_as, offset):
    263         return super(PoolTagCheck, self).check(
--> 264             buffer_as, offset + self.tag_offset)
    265
    266

d:\src\python\rekall\rekall-core\rekall\scan.pyc in check(self, buffer_as, offset)
    172         # Just check the buffer without needing to copy it on slice.
    173         buffer_offset = buffer_as.get_buffer_offset(offset) + self.needle_offset
--> 174         if buffer_as.data.startswith(self.needle, buffer_offset):
    175             return self.needle
    176

TypeError: slice indices must be integers or None or have an __index__ method
> d:\src\python\rekall\rekall-core\rekall\scan.py(174)check()
    172         # Just check the buffer without needing to copy it on slice.
    173         buffer_offset = buffer_as.get_buffer_offset(offset) + self.needle_offset
--> 174         if buffer_as.data.startswith(self.needle, buffer_offset):
    175             return self.needle
    176

ipdb> print repr(self.needle), repr(buffer_offset)
'Proc' <No member>
ipdb>
```

**Comment by brakmic** [comment]
Forgot to mention that I'm now running **rekal -v live** on my Win 10 x64.
