### ISSUE TITLE
LazyRepetition error with artifact_collector on Live

### ISSUE THREAD

**Issue by DeKe42** [google/rekall#285]
Hi,

I am currently trying to use rekall as a library to gather some triage data. I wrote the following artifact:

```
name: netscan
doc: Network connections
sources:
    - type: REKALL_EFILTER
      attributes:
          query: >-
            SELECT pid, protocol, remote_addr, state, created, local_addr, owner from netscan(scan_physical: True)
          type_name: RekallNETSCAN
          image_type:
            - Windows

          fields:
            - name: pid
              type: int 
            - name: protocol
              type: unicode
            - name: local_addr
              type: unicode
            - name: remote_addr
              type: unicode 
            - name: state
              type: unicode
            - name: owner
              type: unicode
            - name: created
              type: unicode
```

If I use this artifact on a live system (if it matters, it's a Windows 10 machine, which is why there is scan_physical) like so:

```
artifact_collector(artifact_files=["D:\\EFILTER-Artifacts.yaml"], artifacts=["netscan"], writer="Zip", output_path="D:\\results.zip")
```

It will work for a while and then error out with the following exception:
`ValueError: LazyRepetition LazyRepetition(generator_func=<bound method WinNetscan.collect_as_dicts of Plugin: netscan (WinNetscan)>, value_type=<type 'dict'>) was previously able to iterate its generator up to idx 258, but this time iteration stopped after idx 253! Generator function <bound method WinNetscan.collect_as_dicts of Plugin: netscan (WinNetscan)> is not stable.`
Stacktrace is attached: [Exception.txt](https://github.com/google/rekall/files/1285219/Exception.txt)

I guess this is caused by changing network connections on a live system. Or am I doing something wrong?

Thanks!

**Comment by scudette** [comment]
This is a bug in efilter:

https://github.com/google/dotty/blob/b145131499be0c4b755fc2e2ac19be11a50bce6a/efilter/ext/lazy_repetition.py#L101

which was fixed in the latest release. You can either install efilter
from our project
https://github.com/rekall-innovations/dotty

or just install the latest Rekall.

Thanks
Michael.

**Comment by DeKe42** [comment]
Hi Michael, thanks for the quick reply, as usual!

It indeed works if I use the packaged x64 release (1.7 RC1) from the website. It does not work if I use the pip-installed version. I made sure to update everything that I think might be connected to rekall and efilter. This is an exerpt from `pip list`:
```
rekall (1.7.1.dev9, d:\cmc\rekall)
rekall-agent (1.7.1.dev5, d:\cmc\rekall\rekall-agent)
rekall-capstone (3.0.4.post2)
rekall-core (1.7.1.dev9, d:\cmc\rekall\rekall-core)
rekall-efilter (1.5.2, d:\cmc\dotty)
rekall-lib (1.7.1.dev9, d:\cmc\rekall\rekall-lib)
rekall-yara (3.4.0.1)
```

Using this version, I still get the error. Is there something else that's changed in the standalone version?

**Comment by DeKe42** [comment]
After debugging this a little, I'm not sure while the standalone version does not have this problem..

The netscan-plugin is evaluated two times
- first in `LazyRepetition.count`, which is called by `repeated.isrepeating` and does not do anything with the result
- and again in `solve_map.lazy_map` (solve.py:430)

I cannot claim to understand the efilter-code, but from my  perspective it makes sense that both plugin evaluations (which take some time) will yield different results for something as volatile as network connections.
On the other hand, I could not bring the standalone version to show the same error, so something seems to be different here.

**Comment by scudette** [comment]
I think I know what is happening here. The bug is actually with efilter itself. I sent a bug report upstream but in order to make the Rekall release deadline I had to fork efilter as I indicated above. In order to make it usable to Rekall I renamed the package to 'rekall-efilter':

https://github.com/rekall-innovations/dotty/blob/master/setup.py#L122

The standalone version *only* installs this package and *not* the original efilter package which is why it works. I suspect that when you install it in your own virtualenv, the old efilter is still installed at the same time as the forked rekall-efilter and due to import order its still picking the old one.

So the solution is to pip uninstall efilter in your virtualenv and maybe even make sure your delete the old efilter directory and make sure you install rekall-efilter.

**Comment by DeKe42** [comment]
I'm not sure that is the problem. I already removed efilter from the virtualenv and when I debug the code, I see I'm in the correct source tree of rekall-efilter. I can see the changes from your commit.

If I comment out the checks for the watermark in `lazy_repetition.py`, everything runs. I'm not sure what side effects that may cause.

Is there any way to double-check I'm running the same version of everything as in the standalone?

**Comment by scudette** [comment]
Hmm looks like I did not remove this check. As you say the problem here is that when used in Rekall there is no guarantee that two runs of the same iterator will produce the same result so this check is too strict.

Can you send a PR against the rekall-efilter and we can update that please?

you can check that the two versions are the same by simply going into the virtualenv and running `pip freeze`. The standalone just ships a complete virtualenv in the deb already (with pip etc). You can also just compare the files between a new clean virtualenv and the one shipped in the deb.

**Comment by DeKe42** [comment]
Sure, I sent a rudimentary PR that removes those checks. That seems to resolve all my issues right now.

I looked at the 1.7.0 deb-file, but this one seems to have the check intact. I did not manage to extract the rekal.exe from the Windows standalone version to look at the efilter code there.

**Comment by scudette** [comment]
I think this one is resolved.
