### ISSUE TITLE
OSXPmem: AFF4 extract

### ISSUE THREAD

**Issue by evild3ad** [google/rekall#480]
Hi,

I tried to extract the physical memory stream /dev/pmem from my created AFF4 volume without success.

osxpmem.app/osxpmem  version: 3.0rc1

`sudo osxpmem.app/osxpmem -e /dev/pmem -o /Users/evild3ad/Desktop/Mojave-10.14.2.raw /Users/evild3ad/Desktop/Mojave-10.14.2.aff4
2019-02-07 16:43:47 E Can not specify an export and an output volume at the same time (did you mean --export_dir).
2019-02-07 16:43:47 E Imaging failed with error: -5`

`sudo osxpmem.app/osxpmem -e '*' -D /Users/evild3ad/Desktop/ /Users/evild3ad/Desktop/Mojave-10.14.2.aff4` has no output.

Issue #400 looks similar.

Also `sudo osxpmem.app/osxpmem -l /Users/evild3ad/Desktop/Mojave-10.14.2.aff4` gives me no output.

**Comment by evild3ad** [comment]
When I add the swap files to my AFF4 volume the --list argument shows me only the added swap files: `sudo osxpmem.app/osxpmem -i /private/var/vm/swapfile* -o /Users/evild3ad/Desktop/Mojave-10.14.2.aff4`
`sudo osxpmem.app/osxpmem -l "/Users/evild3ad/Desktop/Mojave-10.14.2.aff4"
aff4://f10f6235-ff77-4d4f-a103-edd72b371185/private/var/vm/swapfile1
aff4://f10f6235-ff77-4d4f-a103-edd72b371185/private/var/vm/swapfile0`

**Comment by evild3ad** [comment]
`sudo osxpmem.app/osxpmem -e '*' -D /Users/evild3ad/Desktop/ /Users/evild3ad/Desktop/Mojave-10.14.2.aff4` exports only the two swap files to my Desktop.

**Comment by evild3ad** [comment]
`./rekal aff4ls /Users/evild3ad/Desktop/Mojave-10.14.2.aff4` works.
3649044480 Map    Physical Memory     aff4://e2279e8f-e10a-4293-b553-5e8a96b1a902/dev/pmem
<snip>

**Comment by evild3ad** [comment]
`./rekal aff4export --dump_dir /Users/evild3ad/Desktop/dump/ /Users/evild3ad/Desktop/Mojave-10.14.2.aff4` fails.
Error -3 while decompressing data: incorrect header check

**Comment by scudette** [comment]
Hi - version 3.0rc1 is quite. I just noticed that it was the last version we released for mac. Sorry about that. I just rebuilt git head for mac (v3.2) and updated the release page (https://github.com/Velocidex/c-aff4/releases/tag/3.2).  You can try to extract with the latest version or use a more recent version of winpmem (on windows) to extract the same file.

```
osxpmem.app/osxpmem -e '*' -D /Users/evild3ad/Desktop/ /Users/evild3ad/Desktop/Mojave-10.14.2.aff4
```
Should work (you dont need to be root to extract).

**Comment by evild3ad** [comment]
Hi, something is wrong with v3.2.

`sudo osxpmem.app/osxpmem -h
dyld: Library not loaded: @executable_path/libs/libaff4.0.dylib
  Referenced from: /opt/OSXPmem/osxpmem.app/osxpmem
  Reason: image not found
Abort trap: 6`

**Comment by scudette** [comment]
is that file there? It should be at osxpmem.app/libs/libaff4.0.dylib 

```
root@IMacDev:/tmp# unzip osxpmem_3.2.zip
Archive:  osxpmem_3.2.zip
   creating: osxpmem.app/
   creating: osxpmem.app/libs/
  inflating: osxpmem.app/libs/libaff4.0.dylib
  inflating: osxpmem.app/libs/liblz4.1.dylib
  inflating: osxpmem.app/libs/libraptor2.0.dylib
  inflating: osxpmem.app/libs/libsnappy.1.dylib
  inflating: osxpmem.app/libs/liburiparser.1.dylib
  inflating: osxpmem.app/libs/libuuid.16.dylib
  inflating: osxpmem.app/libs/libyaml-cpp.0.6.dylib
   creating: osxpmem.app/MacPmem.kext/
   creating: osxpmem.app/MacPmem.kext/Contents/
   creating: osxpmem.app/MacPmem.kext/Contents/_CodeSignature/
  inflating: osxpmem.app/MacPmem.kext/Contents/_CodeSignature/CodeResources
  inflating: osxpmem.app/MacPmem.kext/Contents/Info.plist
   creating: osxpmem.app/MacPmem.kext/Contents/MacOS/
  inflating: osxpmem.app/MacPmem.kext/Contents/MacOS/MacPmem
  inflating: osxpmem.app/osxpmem
  inflating: osxpmem.app/README.md
root@IMacDev:/tmp# osxpmem.app/osxpmem -h

USAGE:
```

**Comment by evild3ad** [comment]
Downloaded the release again. The extraction of the stream from the AFF4 volume works now. But -l is still not listing the stream inside the AFF4 volume. Will continue with testing ...

**Comment by scudette** [comment]
Ah the -l flag only lists streams of type AFF4_IMAGE_TYPE and the memory image is a map. You should be able to see all streams with the -V flag anyway.

**Comment by evild3ad** [comment]
Ah ok. Thank you!
